### ISSUE TITLE
Appveyor build failing for myDijkstra task 

### ISSUE THREAD

**Issue by thisisashukla** [cvvergara/pgrouting#140]
### Expected behavior and actual behavior

The Appveyor build should pass after the addition of myDijkstra function in the following PRs:
 - https://github.com/cvvergara/pgrouting/pull/138
 - https://github.com/cvvergara/pgrouting/pull/136

### Steps to reproduce the problem

Following are the build links:
 - https://ci.appveyor.com/project/daas-ankur-shukla/pgrouting/build/2.4.20
 -

**Comment by cvvergara** [comment]
suggested changes:
```
on vickyDijkstra.c this:

 PGDLLEXPORT Datum vickyDijkstra(PG_FUNCTION_ARGS);
PG_FUNCTION_INFO_V1(vickyDijkstra);
```
instead of this:
```
PG_FUNCTION_INFO_V1(vickyDijkstra);
 PGDLLEXPORT Datum vickyDijkstra(PG_FUNCTION_ARGS);
```
on vickyDijkstra_driver.cpp this: (order of the includes is important)

```
#include "./vickyDijkstra_driver.h"

#include <sstream>
#include <deque>
#include <vector>

#include "dijkstra/pgr_dijkstra.hpp"

#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"
```

instead of this:
```
#include <sstream>
#include <deque>
#include <vector>

#include "./vickyDijkstra_driver.h"

#include "cpp_common/pgr_alloc.hpp"
#include "cpp_common/pgr_assert.h"

#include "dijkstra/pgr_dijkstra.hpp"
```

**Comment by cvvergara** [comment]
BTW I am working on fixing the template
in the new version the driver header will be located on:
include/drivers/FUNCTION_NAME/
