### ISSUE TITLE
2.1.1 coding tasks

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/pgrouting#60]
Related [Issue 688](https://github.com/pgRouting/pgrouting/issues/688)

branches
- https://github.com/cvvergara/pgrouting/tree/release/2.1.1
- https://github.com/pgRouting/pgrouting/tree/release/2.1.1
## preparation before coding
- [x] Download g++ 4.4
- [x] Set up Jenkins to track this branch (checks on 9.6)
- [x] Set up travis to track this branch
- [x] change the version number
  - [x] CmakeLists
  - [ ] docs
  - [x] pre-commit
- [x] results of running tests ok, on travis and jenkins
- [x] check the upgrade from 2.0.0 works
## coding
- [x] heap_formTuple  ->  heap_formTuple
- [x] change NULL -> bool
- [x]  fix extern "C" {
## C++
- [x] Range loops -> iterator loops & remove lambda functions
  - [x] basePath_SSEC.hpp
  - [x] pgr_dijkstra.hpp
  - [x] baseGraph.hpp
## sql
- [x] add wrappers where possible based on fixed functions to get better results
  - [x] kdijstraPath
  - [x] jdikstraCost
  - [x]  vidsToDmatrix
## typos
- [x] fix typos

**Comment by woodbri** [comment]
I think we might want to look at two different approaches to solving this problem
* get pgr 2.1 to compile on g++ 4.4 and working with pg 9.6
  * The 2.1 path has a few range for loops and needs tuple issue fixed.
* get pgr 2.2 to compile on g++ 4.4 and working with pg 9.6
  * The 2.2 path has more range for loops but already works for 9.6
  * this also has the advantage that lots of other fixes are in the code.

The pgr 2.2 path could be assessed by download the 4.4 compiler and seeing how many files need to be changed.

This is only an idea as it might be faster to do the 2.2 path and give better code to the CENTOS users. I'll leave the decision to @cvvergara

**Comment by cvvergara** [comment]
2.1.0 Range loops
```
cat src/*/src/* | grep 'for (' | grep ':'
  for (tie(ei, eend) = boost::edges(graph); ei != eend; ei++) {
  for (std::size_t j = 0; j < count; ++j)
      for (boost::tie(out, out_end) = out_edges(g_from, graph);
      for (boost::tie(out, out_end) = out_edges(g_vertex, graph);
          for (boost::tie(in, in_end) = in_edges(g_vertex, graph);
            for (boost::tie(out, out_end) = out_edges(*vi, graph);
      for (const auto source: sources) {
        for (boost::tie(out_i, out_end) = boost::out_edges(from, graph);
   for (const Path &path : paths) {
    for (auto const &e : p2.path) {
    for (const auto &p1 : paths) {
    for (const Path &e : paths) {
   for (const Path &path : paths) {
    for (auto const &e : p2.path) {
    for (const auto &p1 : paths) {
    for (const Path &e : paths) {
      for (const auto &v_source : v_sources) {
      for (const auto &start : start_vertex) {
      for (const auto &v_source : v_sources) {
  for (std::size_t j = 0; j < count; ++j)
    for (std::size_t j = 0; j < count; ++j)
    for (std::size_t j = 0; j < count; ++j)
cat: src/tsp/src/OBSOLETE: Is a directory
        elog(ERROR, "many2many_dijkstra_dm: SPI_prepare failed for (%s)", sql);
        for (const auto &path : paths) {
          for (const auto &path :  paths) {
  for (std::size_t j = 0; j < count; ++j)
                //for (std::map< CVRPTWMove*,int >::iterator it = m_mpMoveFrequency.begin();it!=m_mpMoveFrequency.end();++it)
```

**Comment by cvvergara** [comment]
2.1
```
cat src/*/src/* | grep 'for *(' | grep ':' | wc -l
27
```

2.2.4
```
cat src/*/src/* | grep 'for *(' | grep ':' | wc -l
cat: src/linecommand/src/performance: Is a directory
cat: src/tsp/src/OBSOLETE: Is a directory
93
```

**Comment by cvvergara** [comment]
```
cat src/*/src/* | grep 'for *(' | grep ':' | wc -l
cat: src/linecommand/src/performance: Is a directory
194
```

**Comment by woodbri** [comment]
Here are some better queries:
```
$ # list the files that might need to change
$ grep -l -P 'for\s*\([^:)]+:' src/*/src/*

$ # list the lines that might need to change
$ grep -P 'for\s*\([^:)]+:' src/*/src/*
```

**Comment by cvvergara** [comment]
Also lambdas are a problem:
On this code:
```
    sort(result.path.begin(), result.path.end(),
      [](const pgr_path_element3_t &e1, const pgr_path_element3_t &e2)->bool {   //line 115
         return e1.vertex < e2.vertex;
      });
```

```
/home/vicky/pgrouting/pgrouting/vicky/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before ‘[’ token
/home/vicky/pgrouting/pgrouting/vicky/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before ‘]’ token
```

**Comment by cvvergara** [comment]
@woodbri the results of
grep -l -P 'for\s*\([^:)]+:' src/*/src/*
that does not give me how many Range loops I would have to modify

**Comment by cvvergara** [comment]
looks like only has 2 lambdas:
```
cat src/*/src/* | grep '\[ *\] *('
      [](const pgr_path_element3_t &e1, const pgr_path_element3_t &e2)->bool { 
      [](const pgr_path_element3_t &e1, const pgr_path_element3_t &e2)->bool { 
```

**Comment by woodbri** [comment]
Try this one for the file and the count:

```
$ # list the files that might need to change and count of line
$ grep -c -P 'for\s*\([^:)]+:' src/*/src/* | grep -v ':0'
```

**Comment by cvvergara** [comment]
made a tag
 https://github.com/pgRouting/pgrouting/releases/tag/experiment%2Fg%2B%2B4.4compilable-lw
